// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFEay1y5nbpqZ01m8ptpcn9e3rnxCo9wY',
    appId: '1:73962691990:web:bd60a380d432681d6251b7',
    messagingSenderId: '73962691990',
    projectId: 'phoneauth-86911',
    authDomain: 'phoneauth-86911.firebaseapp.com',
    storageBucket: 'phoneauth-86911.appspot.com',
    measurementId: 'G-0BFBJTC2PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJhjAvrm1kOHroLd4tEVMhbpZyr9t1uP8',
    appId: '1:73962691990:android:c9443c694f5868966251b7',
    messagingSenderId: '73962691990',
    projectId: 'phoneauth-86911',
    storageBucket: 'phoneauth-86911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Z1sZ6__qKjz5fS8QzdgmDNIEP-UrcaI',
    appId: '1:73962691990:ios:d80b869daba077176251b7',
    messagingSenderId: '73962691990',
    projectId: 'phoneauth-86911',
    storageBucket: 'phoneauth-86911.appspot.com',
    iosBundleId: 'com.example.phoneauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Z1sZ6__qKjz5fS8QzdgmDNIEP-UrcaI',
    appId: '1:73962691990:ios:d80b869daba077176251b7',
    messagingSenderId: '73962691990',
    projectId: 'phoneauth-86911',
    storageBucket: 'phoneauth-86911.appspot.com',
    iosBundleId: 'com.example.phoneauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFEay1y5nbpqZ01m8ptpcn9e3rnxCo9wY',
    appId: '1:73962691990:web:2caba2f92f1d07e16251b7',
    messagingSenderId: '73962691990',
    projectId: 'phoneauth-86911',
    authDomain: 'phoneauth-86911.firebaseapp.com',
    storageBucket: 'phoneauth-86911.appspot.com',
    measurementId: 'G-JR21RWD2YE',
  );
}
